module.exports = {
  certificates: require("./certificateModel"),
  course: require("./courseModel"),
  classes: require("./classModel"),
  employees: require("./employeeModel"),
  events: require("./eventModal"),
  lead: require("./newLeadModel"),
  permission: require("./permissionModel"),
  registrationType: require("./registrationModel"),
  roles: require("./roleModel"),
  tongaUsers: require("./tongaUserModel"),
  tradeLevel: require("./tradeModel").tradeLevelModel,
  tradeTypeModel: require("./tradeModel").tradeTypeModel,
  trainers: require("./trainerModel"),
  user: require("./userModel"),
  quotations: require("./quotationModel"),
};
