module.exports = {
  certificates: require("./certificateModel"),
  course: require("./courseModel"),
  classes: require("./classModel"),
  events: require("./eventModal"),
  lead: require("./newLeadModel"),
  permission: require("./permissionModel"),
  registrationType: require("./registrationModel"),
  roles: require("./roleModel"),
  tongaUsers: require("./tongaUserModel"),
  tradeLevel: require("./tradeModel").tradeLevelModel,
  tradeTypeModel: require("./tradeModel").tradeTypeModel,
  trainers: require("./trainerModel"),
  user: require("./userModel"),
  quotations: require("./quotationModel"),
  payRolls: require("./PayrollModel"),
  timesheets: require("./timeSheetModel"),
  leaves: require("./leaveModel"),
  language: require("./languageModel"),
  designation: require("./designationModel"),
  constants:require("./constants"),
  
};
