const languagesDataArray = [
  {
    language: {
      welcome: "welcome",
      Dashboard: "Dashboard",
      Lead: "Lead",
      Customer: "Customer",
      Finance: "Finance",
      Admin: "Admin",
      HRMS: "HRMS",
      Settings: "Settings",
      Payouts: "Payouts",
      All: "All",
      New: "New",
      Pending: "Pending",
      Assign: "Assign",
      Completed: "Completed",
      Search: "Search",
      Course_Management: "Course Management",
      Schedule: "Schedule",
      Calendar: "Calendar",
      Trainers: "Trainers",
      Holidays: "Holidays",
      Courses: "Courses",
      Class: "Class",
      Attendance: "Attendance",
      Feedback: "Feedback",
      Constants: "Constants",
      My_Courses: "My Courses",
      Top_Trainers: "Top Trainers",
      New_Customers: "New Customers",
      Course_List: "Course List",
      Customer_Nabagement: "Customer Management",
      customer_List: "customer List",
      Lead_List: "Lead List",
      Select_Company: "Select Company",
      Add_New: "Add New",
      Clear_Filters: "Clear Filters",
      Enter_Company_Name: "Enter Company Name",
      Please_Enter_Company_Name: "Please Enter Company Name",
      Registration_Type: "Registration Type",
      Trade_Level: "Trade Level",
      Trade_Types: "Trade Types",
      Certificate_Generation: "Certificate Generation",
      Quotation_Management: "Quotation Management",
      Sales_Quotation: "Sales Quotation",
      Invoice_Management: "Invoice Management",
      User_Managment: "User Managment",
      Roles_and_Permission: "Roles and Permission",
      Employee_Management: "Employee Management",
      Payroll_Maagment: "Payroll Maagment",
      Leave_Management: "Leave Management",
      Timesheet_Tracking: "Timesheet Tracking",
      Multi_Language: "Multi Language",
      System_Configuration: "System Configuration",

      Course: "Course",
      Category: "Category",
      Classes: "Classes",
      Trainer: "Trainer",
      Customers: "Customers",
      Name: "Name",
      User: "User",
      Role: "Role",
      Status: "Status",
      Mobile: "Mobile",
      Email: "Email",
      Seat: "Seat",
      Duration: "Duration",
      Amount: "Amount",
      DOB: "DOB",
      Designation: "Designation",
      Date: "Date",
      Time: "Time",
      Grade: "Grade",
      Attachment: "Attachment",
      Remarks: "Remarks",
      Position: "Position",
      Phone: "Phone",
      Department: "Department",
      Quantity: "Quantity",
      Allowances: "Allowances",
      Deductions: "Deductions",
      Shift: "Shift",
      Courses: "Courses",
      Completed: "Completed",
      Subject: "Subject",
      Last_Updated: "Last Updated",
      Assigned_To: "Assigned To",
      Created_At: "Created At",
      User_Id: "User Id",
      User_Name: "User Name",
      User_Right: "User Right",
      Registration_Type: "Registration Type",
      Company_Name: "Company Name",
      Contact_Person: "Contact Person",
      Trade_Type: "Trade Type",
      Trade_Level: "Trade Level",
      Registration_Name: "Registration Name",
      Price_In_Dollar: "Price ($)",
      Course_Name: "Course Name",
      Start_Date: "Start Date",
      End_Date: "End Date",
      Class_Timing: "Class Timing",
      Purchase_Date: "Purchase Date",
      Trainer_ID: "Trainer ID",
      Email_ID: "Email ID",
      Certificate_Number: "Certificate Number",
      Employee_ID: "Employee ID",
      Join_Date: "Join Date",
      Unit_Price: "Unit Price",
      Discount_In_Percentage: "Discount(%)",
      Customer_Name: "Customer Name",
      Created_on: "Created on",
      Employee_Name: "Employee Name",
      Basic_Salary: "Basic Salary",
      Net_Salary: "Net Salary",
      Hours_Worked: "Hours Worked",
      Overtime_Hours: "Overtime Hours",
      Leave_Type: "Leave Type",
      Course_Title: "Course Title",
      Email_Type: "Email Type",
      Mobile_No: "Mobile No",
      Name_of_Participant: "Name of Participant",
      Name_Of_Trainee: "Name Of Trainee",
      NRIC_FIN_No: "NRIC/ FIN No",
      Registration_No_Submission_No_CoreTrade_Multi_Skilling_Direct_R1:
        "Registration No / Submission No (CoreTrade / Multi-Skilling / Direct R1)",
      Trainees_Attendance_Signature: "Trainee's Attendance (Signature)",
      Results_P_f: "Results (P/f) *",
      Gross_Amount_In_Dollar: "Gross Amount($)",
      Quotation_No: "Quotation No",
      Sales_Quotation_No: "Sales Quotation No",
      Invoice_Quotation_No: "Invoice Quotation No",
      Lec_In_Week: "Lec In Week",
      Name_of_Participant: "Name of Participant",
      Participants_Mobile: "Participant's Mobile",
      Participants_Name: "Participant's Name",
      Date_Of_Completion: "Date Of Completion",
      CoreTrade_Registration_No: "CoreTrade Registration No",
      Actions: "Actions",
    },
    name: "English",
    code: "en",
    status: "active",
  },
  // {
  //   language: {
  //     welcome: "欢迎",
  //     Dashboard: "仪表板",
  //     Lead: "带领",
  //     Customer: "顾客",
  //     Finance: "金融",
  //     Admin: "行政",
  //     HRMS: "人力资源管理系统",
  //     Settings: "设置",
  //     Payouts: "支出",
  //     All: "全部",
  //     New: "新的",
  //     Pending: "待办的",
  //     Assign: "分配",
  //     Completed: "完全的",
  //     Search: "搜索",
  //     Schedule: "日程",
  //     Calendar: "日历",
  //     Trainers: "运动鞋",
  //     Holidays: "假期",
  //     Courses: "培训班",
  //     Class: "班级",
  //     Attendance: "出席率",
  //     Feedback: "反馈",
  //     Course_Management: "课程管理",
  //     Constants: "常数",
  //     My_Courses: "我的课程",
  //     Top_Trainers: "顶级培训师",
  //     New_Customers: "新客户",
  //     Course_List: "课程列表",
  //     Customer_Nabagement: "用户管理",
  //     customer_List: "客户名单",
  //     Lead_List: "潜在客户名单",
  //     Select_Company: "选择公司",
  //     Add_New: "添新",
  //     Clear_Filters: "清除过滤器",
  //     Enter_Company_Name: "输入公司名称",
  //     Please_Enter_Company_Name: "请输入公司名称",
  //     Registration_Type: "注册类型",
  //     Trade_Level: "贸易水平",
  //     Trade_Types: "贸易类型",
  //     Certificate_Generation: "证书生成",
  //     Quotation_Management: "报价管理",
  //     Sales_Quotation: "销售报价",
  //     Invoice_Management: "发票管理",
  //     User_Managment: "用户管理",
  //     Roles_and_Permission: "角色和权限",
  //     Employee_Management: "员工管理",
  //     Payroll_Maagment: "薪资管理",
  //     Leave_Management: "休假管理",
  //     Timesheet_Tracking: "时间表跟踪",
  //     Multi_Language: "多语言",
  //     System_Configuration: "系统配置",
  //     Course: "课程",
  //     Category: "类别",
  //     Classes: "课程",
  //     Trainer: "训练师",
  //     Customers: "顾客",
  //     Name: "姓名",
  //     User: "用户",
  //     Role: "角色",
  //     Status: "地位",
  //     Mobile: "移动的",
  //     Email: "电子邮件",
  //     Seat: "座位",
  //     Duration: "期间",
  //     Amount: "数量",
  //     DOB: "出生日期",
  //     Designation: "指定",
  //     Date: "日期",
  //     Time: "时间",
  //     Grade: "年级",
  //     Attachment: "依恋",
  //     Remarks: "评论",
  //     Position: "位置",
  //     Phone: "电话",
  //     Department: "部门",
  //     Quantity: "数量",
  //     Allowances: "津贴",
  //     Deductions: "扣除额",
  //     Shift: "转移",
  //     Courses: "培训班",
  //     Completed: "完全的",
  //     Subject: "主题",
  //     Last_Updated: "最近更新时间",
  //     Assigned_To: "分配给",
  //     Created_At: "创建于",
  //     User_Id: "bumbunnu",
  //     User_Name: "bumbunnu",
  //     User_Right: "bumbunnu",
  //     Registration_Type: "bumbunnu",
  //     Company_Name: "bumbunnu",
  //     Contact_Person: "bumbunnu",
  //     Trade_Type: "bumbunnu",
  //     Trade_Level: "bumbunnu",
  //     Registration_Name: "bumbunnu",
  //     Price_In_Dollar: "bumbunnu",
  //     Course_Name: "bumbunnu",
  //     Start_Date: "bumbunnu",
  //     End_Date: "bumbunnu",
  //     Class_Timing: "bumbunnu",
  //     Purchase_Date: "bumbunnu",
  //     Trainer_ID: "bumbunnu",
  //     Email_ID: "bumbunnu",
  //     Certificate_Number: "bumbunnu",
  //     Employee_ID: "bumbunnu",
  //     Join_Date: "bumbunnu",
  //     Unit_Price: "bumbunnu",
  //     Discount_In_Percentage: "bumbunnu",
  //     Customer_Name: "bumbunnu",
  //     Created_on: "bumbunnu",
  //     Employee_Name: "bumbunnu",
  //     Basic_Salary: "bumbunnu",
  //     Net_Salary: "bumbunnu",
  //     Hours_Worked: "bumbunnu",
  //     Overtime_Hours: "bumbunnu",
  //     Leave_Type: "bumbunnu",
  //     Course_Title: "bumbunnu",
  //     Email_Type: "bumbunnu",
  //     Mobile_No: "bumbunnu",
  //     Name_of_Participant: "bumbunnu",
  //     Name_Of_Trainee: "bumbunnu",
  //     NRIC_FIN_No: "bumbunnu",
  //     Registration_No_Submission_No_CoreTrade_Multi_Skilling_Direct_R1:
  //       "bumbunnu",
  //     Trainees_Attendance_Signature: "bumbunnu",
  //     Results_P_f: "bumbunnu",
  //     Gross_Amount_In_Dollar: "bumbunnu",
  //     Quotation_No: "bumbunnu",
  //     Sales_Quotation_No: "bumbunnu",
  //     Invoice_Quotation_No: "bumbunnu",
  //     Lec_In_Week: "bumbunnu",
  //     Name_of_Participant: "bumbunnu",
  //     Participants_Mobile: "bumbunnu",
  //     Participants_Name: "bumbunnu",
  //     Date_Of_Completion: "bumbunnu",
  //     CoreTrade_Registration_No: "bumbunnu",
  //     Actions: "bumbunnu",
  //   },
  //   name: "Chinese",
  //   code: "zh-CN",
  // },
];

module.exports = {
  languagesDataArray,
};
