module.exports = {
  roleName: "Admin",
  employeeManagement: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  finManagement: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  payroll: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  leaveManagement: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  timesheet: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  userManagement: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  role: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  customer: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  lead: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  trainer: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  holiday: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  registrationType: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  tradeLevel: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  tradeType: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  courses: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  class: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
  certificateGeneration: {
    create: true,
    read: true,
    write: true,
    delete: true,
  },
};
